version: "3"

services:
  twcmanager:
    image: twcmanager/twcmanager:latest
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /etc/twcmanager:/etc/twcmanager
      - /etc/localtime:/etc/localtime:ro
